### ISSUE TITLE
[RFE] Ratelimiting

### ISSUE THREAD

**Issue by dopykuh** [muhproductions/muh#3]
Provide a http flood protection. 
The current idea is to limit by gist/snippet size and amount of requests.

**Comment by timmyArch** [comment]
added in b79ebd35098a8bbd1c05d11fbcdc50de8e82a6d9

**Comment by dopykuh** [comment]
As already in #7 , the ratelimit should be handle multiple caching tiers.

**Comment by dopykuh** [comment]
closed due to b416730
